import { useEffect, useMemo, useState } from 'react';
import LanguageWelcome from '../components/LanguageWelcome';
import { LANGUAGES, LANGUAGE_STORAGE_KEY } from './languageConfig';
import LanguageContext from './languageState';

const copy = {
  en: {
    offlineNotice: 'Offline. Previously opened pages remain available.',
    chooseLanguage: 'Choose your language', languageHelp: 'The library and Sarathi will use this language.', continue: 'Continue', changeLanguage: 'Change language',
    scriptureLibrary: 'Scripture Library', read: 'Read', search: 'Search scripture', askSarathi: 'Ask Sarathi', home: 'Home', gita: 'Gita', ramayana: 'Ramayana', openingPage: 'Opening page',
    sarathiWelcome: 'Ask about a verse, teaching, or difficult idea. I will answer from the texts in this library.', noAnswer: 'No answer was returned.', sarathiError: 'Sarathi could not respond right now.',
    scriptureGuide: 'Scripture guide', you: 'You', sources: 'Sources', looking: 'Looking through the texts…', tryAsking: 'Try asking', askPlaceholder: 'Ask about a verse or idea', groundedNote: 'Answers include chapter and verse', ask: 'Ask', working: 'Working…',
    promptDuty: 'What does the Gita teach about duty?', promptDetachment: 'Explain detachment in simple words.', promptDecision: 'Which verses can help with a difficult decision?',
    libraryName: 'Gyan Sutra Library', heroTitleBefore: 'Read the ', heroTitleHighlight: 'Bhagavad Gita', heroTitleAfter: ' and Ramayana', heroSubtitle: 'Original Sanskrit with transliteration, available translations, and clear commentary.', readGita: 'Read the Bhagavad Gita', browseLibrary: 'Browse the library', dailyDarshan: 'Daily Darshan', todaysVerse: 'Today’s verse', preparingVerse: 'Preparing today’s verse', meaning: 'Meaning', readFullVerse: 'Read full verse', availableRead: 'Available to read', chooseText: 'Choose a text', chooseTextHelp: 'Open a text, choose a chapter, and continue at your own pace.', chapters18: '18 chapters', kandas7: '7 kandas', gitaDescription: 'Krishna and Arjuna discuss duty, action, devotion, and self-knowledge.', ramayanaDescription: 'Read the account of Rama through exile, separation, war, and return.', inPreparation: 'In preparation: Upanishads, Mahabharata, and Puranas.', dailyUnavailable: 'Today’s verse will return soon.', continueGita: 'You can continue reading the Bhagavad Gita in the meantime.', browseGita: 'Browse the Bhagavad Gita',
    chapter: 'Chapter', verse: 'Verse', kanda: 'Kanda', sarga: 'Sarga', shloka: 'Shloka', relevance: 'match', keyVocabulary: 'Key Vocabulary', simpleMeaning: 'Simple Meaning', commentary: 'Commentary', sourceCount: 'sources', translationUnavailable: 'A verified translation in your selected language is not available yet.', askVerseHelp: 'Ask Sarathi to explain this verse in your language.', askAboutVerse: 'Ask about this verse',
  },
  hi: {
    offlineNotice: 'ऑफ़लाइन। पहले खोले गए पृष्ठ उपलब्ध रहेंगे।',
    chooseLanguage: 'अपनी भाषा चुनें', languageHelp: 'पुस्तकालय और सारथि इसी भाषा का उपयोग करेंगे।', continue: 'आगे बढ़ें', changeLanguage: 'भाषा बदलें', scriptureLibrary: 'शास्त्र पुस्तकालय', read: 'पढ़ें', search: 'शास्त्र खोजें', askSarathi: 'सारथि से पूछें', home: 'मुखपृष्ठ', gita: 'गीता', ramayana: 'रामायण', openingPage: 'पृष्ठ खुल रहा है', sarathiWelcome: 'किसी श्लोक, शिक्षा या कठिन विचार के बारे में पूछें। मैं इस पुस्तकालय के ग्रंथों के आधार पर उत्तर दूँगा।', noAnswer: 'कोई उत्तर प्राप्त नहीं हुआ।', sarathiError: 'सारथि अभी उत्तर नहीं दे सका।', scriptureGuide: 'शास्त्र मार्गदर्शक', you: 'आप', sources: 'स्रोत', looking: 'ग्रंथों में खोज रहा हूँ…', tryAsking: 'यह पूछकर देखें', askPlaceholder: 'किसी श्लोक या विचार के बारे में पूछें', groundedNote: 'उत्तर में अध्याय और श्लोक के संदर्भ शामिल हैं', ask: 'पूछें', working: 'उत्तर तैयार हो रहा है…', promptDuty: 'गीता कर्तव्य के बारे में क्या सिखाती है?', promptDetachment: 'अनासक्ति को सरल शब्दों में समझाइए।', promptDecision: 'कठिन निर्णय में कौन-से श्लोक सहायता कर सकते हैं?', libraryName: 'ज्ञान सूत्र पुस्तकालय', heroTitleBefore: '', heroTitleHighlight: 'भगवद्गीता', heroTitleAfter: ' और रामायण पढ़ें', heroSubtitle: 'मूल संस्कृत, लिप्यंतरण, उपलब्ध अनुवाद और स्पष्ट व्याख्या के साथ।', readGita: 'भगवद्गीता पढ़ें', browseLibrary: 'पुस्तकालय देखें', dailyDarshan: 'दैनिक दर्शन', todaysVerse: 'आज का श्लोक', preparingVerse: 'आज का श्लोक तैयार हो रहा है', meaning: 'अर्थ', readFullVerse: 'पूरा श्लोक पढ़ें', availableRead: 'पढ़ने के लिए उपलब्ध', chooseText: 'ग्रंथ चुनें', chooseTextHelp: 'ग्रंथ खोलें, अध्याय चुनें और अपनी गति से पढ़ें।', chapters18: '18 अध्याय', kandas7: '7 काण्ड', gitaDescription: 'कृष्ण और अर्जुन कर्तव्य, कर्म, भक्ति और आत्मज्ञान पर संवाद करते हैं।', ramayanaDescription: 'राम के वनवास, वियोग, युद्ध और वापसी की कथा पढ़ें।', inPreparation: 'तैयारी में: उपनिषद, महाभारत और पुराण।', dailyUnavailable: 'आज का श्लोक शीघ्र लौटेगा।', continueGita: 'तब तक आप भगवद्गीता पढ़ना जारी रख सकते हैं।', browseGita: 'भगवद्गीता देखें', chapter: 'अध्याय', verse: 'श्लोक', kanda: 'काण्ड', sarga: 'सर्ग', shloka: 'श्लोक', relevance: 'मिलान', keyVocabulary: 'मुख्य शब्दार्थ', simpleMeaning: 'सरल अर्थ', commentary: 'व्याख्या', sourceCount: 'स्रोत', translationUnavailable: 'आपकी चुनी हुई भाषा में प्रमाणित अनुवाद अभी उपलब्ध नहीं है।', askVerseHelp: 'सारथि से इस श्लोक को आपकी भाषा में समझाने के लिए कहें।', askAboutVerse: 'इस श्लोक के बारे में पूछें',
  },
  bn: {
    offlineNotice: 'অফলাইন। আগে খোলা পৃষ্ঠাগুলি পাওয়া যাবে।',
    chooseLanguage: 'আপনার ভাষা বেছে নিন', languageHelp: 'গ্রন্থাগার ও সারথি এই ভাষা ব্যবহার করবে।', continue: 'এগিয়ে যান', changeLanguage: 'ভাষা পরিবর্তন করুন', scriptureLibrary: 'শাস্ত্র গ্রন্থাগার', read: 'পড়ুন', search: 'শাস্ত্র খুঁজুন', askSarathi: 'সারথিকে জিজ্ঞাসা করুন', home: 'মূলপাতা', gita: 'গীতা', ramayana: 'রামায়ণ', openingPage: 'পৃষ্ঠা খুলছে', sarathiWelcome: 'কোনো শ্লোক, শিক্ষা বা কঠিন ভাবনা সম্পর্কে জিজ্ঞাসা করুন। আমি এই গ্রন্থাগারের পাঠের ভিত্তিতে উত্তর দেব।', noAnswer: 'কোনো উত্তর পাওয়া যায়নি।', sarathiError: 'সারথি এখন উত্তর দিতে পারছে না।', scriptureGuide: 'শাস্ত্র সহায়ক', you: 'আপনি', sources: 'উৎস', looking: 'গ্রন্থগুলিতে খুঁজছি…', tryAsking: 'জিজ্ঞাসা করে দেখুন', askPlaceholder: 'কোনো শ্লোক বা ভাবনা সম্পর্কে জিজ্ঞাসা করুন', groundedNote: 'উত্তরে অধ্যায় ও শ্লোকের উল্লেখ থাকে', ask: 'জিজ্ঞাসা করুন', working: 'উত্তর তৈরি হচ্ছে…', promptDuty: 'গীতা কর্তব্য সম্পর্কে কী শিক্ষা দেয়?', promptDetachment: 'অনাসক্তি সহজ ভাষায় বুঝিয়ে দিন।', promptDecision: 'কঠিন সিদ্ধান্তে কোন শ্লোকগুলি সাহায্য করতে পারে?', libraryName: 'জ্ঞান সূত্র গ্রন্থাগার', heroTitleBefore: '', heroTitleHighlight: 'ভগবদ্গীতা', heroTitleAfter: ' ও রামায়ণ পড়ুন', heroSubtitle: 'মূল সংস্কৃত, লিপ্যন্তর, উপলব্ধ অনুবাদ ও স্পষ্ট ব্যাখ্যাসহ।', readGita: 'ভগবদ্গীতা পড়ুন', browseLibrary: 'গ্রন্থাগার দেখুন', dailyDarshan: 'দৈনিক দর্শন', todaysVerse: 'আজকের শ্লোক', preparingVerse: 'আজকের শ্লোক প্রস্তুত হচ্ছে', meaning: 'অর্থ', readFullVerse: 'সম্পূর্ণ শ্লোক পড়ুন', availableRead: 'পড়ার জন্য উপলব্ধ', chooseText: 'গ্রন্থ বেছে নিন', chooseTextHelp: 'একটি গ্রন্থ খুলুন, অধ্যায় বেছে নিন এবং নিজের গতিতে পড়ুন।', chapters18: '১৮ অধ্যায়', kandas7: '৭ কাণ্ড', gitaDescription: 'কৃষ্ণ ও অর্জুন কর্তব্য, কর্ম, ভক্তি ও আত্মজ্ঞান নিয়ে আলোচনা করেন।', ramayanaDescription: 'রামের বনবাস, বিচ্ছেদ, যুদ্ধ ও প্রত্যাবর্তনের কাহিনি পড়ুন।', inPreparation: 'প্রস্তুতিতে: উপনিষদ, মহাভারত ও পুরাণ।', dailyUnavailable: 'আজকের শ্লোক শীঘ্রই ফিরে আসবে।', continueGita: 'এর মধ্যে আপনি ভগবদ্গীতা পড়তে পারেন।', browseGita: 'ভগবদ্গীতা দেখুন', chapter: 'অধ্যায়', verse: 'শ্লোক', kanda: 'কাণ্ড', sarga: 'সর্গ', shloka: 'শ্লোক', relevance: 'মিল', keyVocabulary: 'মূল শব্দার্থ', simpleMeaning: 'সহজ অর্থ', commentary: 'ব্যাখ্যা', sourceCount: 'উৎস', translationUnavailable: 'আপনার নির্বাচিত ভাষায় যাচাইকৃত অনুবাদ এখনও উপলব্ধ নয়।', askVerseHelp: 'সারথিকে এই শ্লোকটি আপনার ভাষায় বুঝিয়ে বলতে বলুন।', askAboutVerse: 'এই শ্লোক সম্পর্কে জিজ্ঞাসা করুন',
  },
  mr: {
    offlineNotice: 'ऑफलाइन। आधी उघडलेली पाने उपलब्ध राहतील.',
    chooseLanguage: 'तुमची भाषा निवडा', languageHelp: 'ग्रंथालय आणि सारथी हीच भाषा वापरतील.', continue: 'पुढे जा', changeLanguage: 'भाषा बदला', scriptureLibrary: 'धर्मग्रंथालय', read: 'वाचा', search: 'धर्मग्रंथ शोधा', askSarathi: 'सारथीला विचारा', home: 'मुखपृष्ठ', gita: 'गीता', ramayana: 'रामायण', openingPage: 'पृष्ठ उघडत आहे', sarathiWelcome: 'श्लोक, शिकवण किंवा कठीण कल्पनेबद्दल विचारा. मी या ग्रंथालयातील ग्रंथांच्या आधारे उत्तर देईन.', noAnswer: 'उत्तर मिळाले नाही.', sarathiError: 'सारथी सध्या उत्तर देऊ शकला नाही.', scriptureGuide: 'धर्मग्रंथ मार्गदर्शक', you: 'तुम्ही', sources: 'स्रोत', looking: 'ग्रंथांमध्ये शोधत आहे…', tryAsking: 'हे विचारून पहा', askPlaceholder: 'श्लोक किंवा कल्पनेबद्दल विचारा', groundedNote: 'उत्तरात अध्याय व श्लोकाचे संदर्भ असतात', ask: 'विचारा', working: 'उत्तर तयार होत आहे…', promptDuty: 'गीता कर्तव्याबद्दल काय शिकवते?', promptDetachment: 'अनासक्ती सोप्या शब्दांत समजावून सांगा.', promptDecision: 'कठीण निर्णयात कोणते श्लोक मदत करू शकतात?', libraryName: 'ज्ञान सूत्र ग्रंथालय', heroTitleBefore: '', heroTitleHighlight: 'भगवद्गीता', heroTitleAfter: ' आणि रामायण वाचा', heroSubtitle: 'मूळ संस्कृत, लिप्यंतरण, उपलब्ध अनुवाद आणि स्पष्ट भाष्यासह।', readGita: 'भगवद्गीता वाचा', browseLibrary: 'ग्रंथालय पहा', dailyDarshan: 'दैनिक दर्शन', todaysVerse: 'आजचा श्लोक', preparingVerse: 'आजचा श्लोक तयार होत आहे', meaning: 'अर्थ', readFullVerse: 'संपूर्ण श्लोक वाचा', availableRead: 'वाचनासाठी उपलब्ध', chooseText: 'ग्रंथ निवडा', chooseTextHelp: 'ग्रंथ उघडा, अध्याय निवडा आणि आपल्या गतीने वाचा.', chapters18: '१८ अध्याय', kandas7: '७ कांड', gitaDescription: 'कृष्ण आणि अर्जुन कर्तव्य, कर्म, भक्ती आणि आत्मज्ञानावर संवाद करतात.', ramayanaDescription: 'रामाचा वनवास, विरह, युद्ध आणि पुनरागमन यांची कथा वाचा.', inPreparation: 'तयारीत: उपनिषदे, महाभारत आणि पुराणे.', dailyUnavailable: 'आजचा श्लोक लवकरच परत येईल.', continueGita: 'तोपर्यंत तुम्ही भगवद्गीता वाचू शकता.', browseGita: 'भगवद्गीता पहा', chapter: 'अध्याय', verse: 'श्लोक', kanda: 'कांड', sarga: 'सर्ग', shloka: 'श्लोक', relevance: 'जुळणारे', keyVocabulary: 'मुख्य शब्दार्थ', simpleMeaning: 'सोपा अर्थ', commentary: 'भाष्य', sourceCount: 'स्रोत', translationUnavailable: 'तुम्ही निवडलेल्या भाषेतील प्रमाणित अनुवाद अद्याप उपलब्ध नाही.', askVerseHelp: 'सारथीला हा श्लोक तुमच्या भाषेत समजावून सांगायला विचारा.', askAboutVerse: 'या श्लोकाबद्दल विचारा',
  },
  te: {
    offlineNotice: 'ఆఫ్‌లైన్। ఇంతకు ముందు తెరిచిన పుటలు అందుబాటులో ఉంటాయి.',
    chooseLanguage: 'మీ భాషను ఎంచుకోండి', languageHelp: 'గ్రంథాలయం మరియు సారథి ఈ భాషనే ఉపయోగిస్తాయి.', continue: 'కొనసాగించండి', changeLanguage: 'భాషను మార్చండి', scriptureLibrary: 'శాస్త్ర గ్రంథాలయం', read: 'చదవండి', search: 'శాస్త్రాలను వెతకండి', askSarathi: 'సారథిని అడగండి', home: 'ముఖపుట', gita: 'గీత', ramayana: 'రామాయణం', openingPage: 'పుట తెరుచుకుంటోంది', sarathiWelcome: 'ఒక శ్లోకం, బోధన లేదా కఠినమైన భావం గురించి అడగండి. ఈ గ్రంథాలయంలోని పాఠాల ఆధారంగా సమాధానం ఇస్తాను.', noAnswer: 'సమాధానం రాలేదు.', sarathiError: 'సారథి ప్రస్తుతం సమాధానం ఇవ్వలేకపోయాడు.', scriptureGuide: 'శాస్త్ర మార్గదర్శి', you: 'మీరు', sources: 'మూలాలు', looking: 'గ్రంథాలలో వెతుకుతున్నాను…', tryAsking: 'ఇలా అడిగి చూడండి', askPlaceholder: 'శ్లోకం లేదా భావం గురించి అడగండి', groundedNote: 'సమాధానాల్లో అధ్యాయం మరియు శ్లోక సూచనలు ఉంటాయి', ask: 'అడగండి', working: 'సమాధానం సిద్ధమవుతోంది…', promptDuty: 'కర్తవ్యం గురించి గీత ఏమి బోధిస్తుంది?', promptDetachment: 'అనాసక్తిని సరళంగా వివరించండి.', promptDecision: 'కఠిన నిర్ణయంలో ఏ శ్లోకాలు సహాయపడతాయి?', libraryName: 'జ్ఞాన సూత్ర గ్రంథాలయం', heroTitleBefore: '', heroTitleHighlight: 'భగవద్గీత', heroTitleAfter: ' మరియు రామాయణం చదవండి', heroSubtitle: 'మూల సంస్కృతం, లిప్యంతరీకరణ, అందుబాటులో ఉన్న అనువాదాలు మరియు స్పష్టమైన వ్యాఖ్యానంతో।', readGita: 'భగవద్గీత చదవండి', browseLibrary: 'గ్రంథాలయాన్ని చూడండి', dailyDarshan: 'నిత్య దర్శనం', todaysVerse: 'నేటి శ్లోకం', preparingVerse: 'నేటి శ్లోకం సిద్ధమవుతోంది', meaning: 'అర్థం', readFullVerse: 'పూర్తి శ్లోకం చదవండి', availableRead: 'చదవడానికి అందుబాటులో ఉన్నాయి', chooseText: 'గ్రంథాన్ని ఎంచుకోండి', chooseTextHelp: 'ఒక గ్రంథాన్ని తెరిచి, అధ్యాయాన్ని ఎంచుకుని, మీ వేగంతో చదవండి.', chapters18: '18 అధ్యాయాలు', kandas7: '7 కాండలు', gitaDescription: 'కృష్ణుడు మరియు అర్జునుడు కర్తవ్యం, కర్మ, భక్తి మరియు ఆత్మజ్ఞానం గురించి చర్చిస్తారు.', ramayanaDescription: 'రాముని వనవాసం, వియోగం, యుద్ధం మరియు తిరిగి రావడం గురించి చదవండి.', inPreparation: 'సిద్ధమవుతున్నవి: ఉపనిషత్తులు, మహాభారతం మరియు పురాణాలు.', dailyUnavailable: 'నేటి శ్లోకం త్వరలో తిరిగి వస్తుంది.', continueGita: 'ఈలోగా మీరు భగవద్గీత చదవవచ్చు.', browseGita: 'భగవద్గీతను చూడండి', chapter: 'అధ్యాయం', verse: 'శ్లోకం', kanda: 'కాండ', sarga: 'సర్గ', shloka: 'శ్లోకం', relevance: 'సరిపోలిక', keyVocabulary: 'ముఖ్య పదార్థాలు', simpleMeaning: 'సరళ అర్థం', commentary: 'వ్యాఖ్యానం', sourceCount: 'మూలాలు', translationUnavailable: 'మీరు ఎంచుకున్న భాషలో ధృవీకరించిన అనువాదం ఇంకా అందుబాటులో లేదు.', askVerseHelp: 'ఈ శ్లోకాన్ని మీ భాషలో వివరించమని సారథిని అడగండి.', askAboutVerse: 'ఈ శ్లోకం గురించి అడగండి',
  },
  ta: {
    offlineNotice: 'இணையம் இல்லை. முன்பு திறந்த பக்கங்கள் கிடைக்கும்.',
    chooseLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்', languageHelp: 'நூலகமும் சாரதியும் இந்த மொழியைப் பயன்படுத்தும்.', continue: 'தொடரவும்', changeLanguage: 'மொழியை மாற்றவும்', scriptureLibrary: 'சாஸ்திர நூலகம்', read: 'படிக்கவும்', search: 'சாஸ்திரங்களில் தேடவும்', askSarathi: 'சாரதியிடம் கேளுங்கள்', home: 'முகப்பு', gita: 'கீதை', ramayana: 'இராமாயணம்', openingPage: 'பக்கம் திறக்கப்படுகிறது', sarathiWelcome: 'ஒரு சுலோகம், போதனை அல்லது கடினமான கருத்தைப் பற்றிக் கேளுங்கள். இந்த நூலகத்தில் உள்ள நூல்களின் அடிப்படையில் பதிலளிப்பேன்.', noAnswer: 'பதில் கிடைக்கவில்லை.', sarathiError: 'சாரதியால் இப்போது பதிலளிக்க முடியவில்லை.', scriptureGuide: 'சாஸ்திர வழிகாட்டி', you: 'நீங்கள்', sources: 'ஆதாரங்கள்', looking: 'நூல்களில் தேடுகிறேன்…', tryAsking: 'இப்படிக் கேட்டுப் பாருங்கள்', askPlaceholder: 'ஒரு சுலோகம் அல்லது கருத்தைப் பற்றிக் கேளுங்கள்', groundedNote: 'பதில்களில் அத்தியாயம் மற்றும் சுலோகக் குறிப்புகள் இருக்கும்', ask: 'கேளுங்கள்', working: 'பதில் தயாராகிறது…', promptDuty: 'கடமை பற்றி கீதை என்ன கற்பிக்கிறது?', promptDetachment: 'பற்றின்மையை எளிய சொற்களில் விளக்குங்கள்.', promptDecision: 'கடினமான முடிவில் எந்தச் சுலோகங்கள் உதவும்?', libraryName: 'ஞான சூத்திர நூலகம்', heroTitleBefore: '', heroTitleHighlight: 'பகவத் கீதை', heroTitleAfter: ' மற்றும் இராமாயணம் படிக்கவும்', heroSubtitle: 'மூல சமஸ்கிருதம், ஒலிபெயர்ப்பு, கிடைக்கும் மொழிபெயர்ப்புகள் மற்றும் தெளிவான விளக்கத்துடன்।', readGita: 'பகவத் கீதையைப் படிக்கவும்', browseLibrary: 'நூலகத்தைப் பார்க்கவும்', dailyDarshan: 'தினசரி தரிசனம்', todaysVerse: 'இன்றைய சுலோகம்', preparingVerse: 'இன்றைய சுலோகம் தயாராகிறது', meaning: 'பொருள்', readFullVerse: 'முழு சுலோகத்தையும் படிக்கவும்', availableRead: 'படிக்கக் கிடைப்பவை', chooseText: 'ஒரு நூலைத் தேர்ந்தெடுக்கவும்', chooseTextHelp: 'ஒரு நூலைத் திறந்து, அத்தியாயத்தைத் தேர்ந்தெடுத்து, உங்கள் வேகத்தில் படிக்கவும்.', chapters18: '18 அத்தியாயங்கள்', kandas7: '7 காண்டங்கள்', gitaDescription: 'கிருஷ்ணரும் அர்ஜுனரும் கடமை, செயல், பக்தி மற்றும் ஆத்ம ஞானம் குறித்து உரையாடுகின்றனர்.', ramayanaDescription: 'இராமரின் வனவாசம், பிரிவு, போர் மற்றும் திரும்புதல் பற்றிப் படிக்கவும்.', inPreparation: 'தயாரிப்பில்: உபநிடதங்கள், மகாபாரதம் மற்றும் புராணங்கள்.', dailyUnavailable: 'இன்றைய சுலோகம் விரைவில் மீண்டும் கிடைக்கும்.', continueGita: 'இதற்கிடையில் பகவத் கீதையைத் தொடர்ந்து படிக்கலாம்.', browseGita: 'பகவத் கீதையைப் பார்க்கவும்', chapter: 'அத்தியாயம்', verse: 'சுலோகம்', kanda: 'காண்டம்', sarga: 'சர்க்கம்', shloka: 'சுலோகம்', relevance: 'பொருத்தம்', keyVocabulary: 'முக்கிய சொற்பொருள்', simpleMeaning: 'எளிய பொருள்', commentary: 'விளக்கவுரை', sourceCount: 'ஆதாரங்கள்', translationUnavailable: 'நீங்கள் தேர்ந்தெடுத்த மொழியில் சரிபார்க்கப்பட்ட மொழிபெயர்ப்பு இன்னும் கிடைக்கவில்லை.', askVerseHelp: 'இந்தச் சுலோகத்தை உங்கள் மொழியில் விளக்குமாறு சாரதியிடம் கேளுங்கள்.', askAboutVerse: 'இந்தச் சுலோகத்தைப் பற்றிக் கேளுங்கள்',
  },
};

function readSavedLanguage() {
  if (typeof window === 'undefined') return null;
  try {
    const saved = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return LANGUAGES.some(({ code }) => code === saved) ? saved : null;
  } catch {
    return null;
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(readSavedLanguage);

  const setLanguage = (code) => {
    if (!LANGUAGES.some((item) => item.code === code)) return;
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, code);
    } catch {
      // The preference still works for this session if storage is unavailable.
    }
    setLanguageState(code);
  };

  useEffect(() => {
    if (!language) return;
    document.documentElement.lang = language;
    document.documentElement.dataset.language = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    languages: LANGUAGES,
    languageInfo: LANGUAGES.find((item) => item.code === language),
    t: (key) => copy[language]?.[key] ?? copy.en[key] ?? key,
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {language ? children : <LanguageWelcome languages={LANGUAGES} onSelect={setLanguage} />}
    </LanguageContext.Provider>
  );
}
